version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./daphne/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./daphne/pong_api:/app
    environment:
      - DEBUG=1
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - web